version: "3.9"

services:
  bot:
    &bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: python3 -m bot
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_started

  taskiq-worker:
    <<: *bot
    command: [taskiq, worker, bot.src.tkq.tkq:broker]

  taskiq-scheduler:
    <<: *bot
    command: [taskiq, scheduler, bot.src.tkq.tkq:scheduler]

  nats:
    image: nats:2.10.17
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    volumes:
      - ./nats-data/data:/data
      - ./nats-data/config/server.conf:/config/server.conf

  redis:
    image: redis:7.2.4
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redis-bot-data:/data

volumes:
  redis-bot-data: